################################################################################
# SCRIPT 03: DESCRIPTIVE ANALYSIS
#
# OBJECTIVE: Produce key descriptive statistics and visualizations to provide
#            a "big picture" overview of the data before hypothesis testing.
#
################################################################################

# 1. LIBRARIES ----------------------------------------------------------------
if (!require(pacman)) install.packages("pacman")
pacman::p_load(dplyr, ggplot2, scales, tidyr, stringr, knitr)

cat("======================================================\n")
cat("=== SCRIPT 03: DESCRIPTIVE ANALYSIS OF AI DEBATES ===\n")
cat("======================================================\n")
cat("Execution Date:", as.character(Sys.Date()), "\n\n")

# 2. LOAD DATA ----------------------------------------------------------------
cat("--- STEP 1: Loading Data ---\\n")

# Load main dataset
tryCatch({
  df <- read.csv("data/ai_categorized_paragraphs_reconciled.csv", stringsAsFactors = FALSE)
  # Recode NA 'Perception.IA' to 'Contextual'
  # NAs represent interventions where AI is mentioned descriptively without a clear tone.
  df$Perception.IA <- ifelse(is.na(df$Perception.IA) | df$Perception.IA == "", "Contextual", df$Perception.IA)
  cat("✓ Main dataset loaded:", nrow(df), "observations\n")
}, error = function(e) {
  stop("ERROR: Main dataset not found. Ensure 'data/ai_categorized_paragraphs_reconciled.csv' exists.")
})

# Load data with political scores (generated by script 02)
tryCatch({
  df_lr <- read.csv("data/h1_analysis_features.csv", stringsAsFactors = FALSE)
  cat("✓ MEP features dataset with political scores loaded.\n\n")
}, error = function(e) {
  stop("ERROR: 'data/h1_analysis_features.csv' not found. Please run '02_hypothesis_analysis.R' first.")
})

# 3. GLOBAL STATISTICS --------------------------------------------------------
cat("--- STEP 2: Global Statistics ---\\n")

# Filter for MEPs with coded perceptions (now including "Contextual")
df_meps <- df %>%
  filter(is_mep == TRUE) %>%
  filter(!is.na(Perception.IA) & Perception.IA %in% c("Optimist", "Pessimist", "Mixed", "Contextual"))

cat("Total interventions:", nrow(df), "\n")
cat("MEP interventions with coded perception:", nrow(df_meps), "\n\n")

# Distribution of perceptions (MEPs only)
perception_meps <- df_meps %>%
  count(Perception.IA) %>%
  mutate(percentage = round((n / sum(n)) * 100, 1)) %>%
  arrange(desc(n))

cat("DISTRIBUTION OF PERCEPTIONS (MEPs):\n")
for(i in 1:nrow(perception_meps)) {
  cat(sprintf("• %s: %d (%.1f%%)\n", perception_meps$Perception.IA[i], perception_meps$n[i], perception_meps$percentage[i]))
}
cat("\n")

# 4. PLOTTING THEME AND SETUP -----------------------------------------------
# Publication-ready theme
theme_publication <- function() {
  theme_minimal(base_size = 12) +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      plot.title = element_text(face = "bold", hjust = 0.5, size = 14, margin = margin(b = 10)),
      plot.subtitle = element_text(hjust = 0.5, size = 11, color = "gray30", margin = margin(b = 15)),
      axis.title = element_text(face = "bold", size = 11),
      axis.text = element_text(size = 10, color = "black"),
      panel.grid.major = element_line(color = "gray85", linewidth = 0.3),
      panel.grid.minor = element_blank(),
      legend.position = "bottom",
      legend.title = element_text(face = "bold", size = 10),
      legend.text = element_text(size = 9),
      plot.margin = margin(15, 15, 15, 15)
    )
}

# Create folder for descriptive figures
if (!dir.exists("figures/descriptive")) dir.create("figures/descriptive", recursive = TRUE)

# 5. GENERATE KEY VISUALIZATIONS ---------------------------------------------
cat("--- STEP 3: Generating Key Visualizations ---\\n")

# FIGURE 1: Distribution of AI Perceptions (Dependent Variable)
cat("Figure 1: Distribution of AI Perceptions...\n")
fig1_data <- df_meps %>%
  count(Perception.IA) %>%
  mutate(
    percentage = n / sum(n) * 100,
    Perception.IA = factor(Perception.IA, levels = c("Pessimist", "Mixed", "Optimist", "Contextual"))
  )

fig1 <- ggplot(fig1_data, aes(x = Perception.IA, y = percentage)) +
  geom_col(aes(fill = Perception.IA), color = "black", width = 0.7, alpha = 0.9) +
  scale_fill_manual(
    values = c("Pessimist" = "gray10", "Mixed" = "gray50", "Optimist" = "gray70", "Contextual" = "gray90"),
    guide = "none"
  ) +
  geom_text(aes(label = paste0(n, " interventions\n", round(percentage, 1), "%")),
            vjust = -0.5, size = 4, fontface = "bold") +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.15)),
    breaks = seq(0, 40, 10),
    name = "Percentage of Interventions (%)",
    labels = scales::percent_format(scale = 100/max(fig1_data$percentage))
  ) +
  scale_x_discrete(name = "AI Perception") +
  labs(
    title = "Distribution of AI Perceptions Among MEPs",
    subtitle = paste0("N = ", sum(fig1_data$n), " coded interventions • European Parliament (2014-2024)")
  ) +
  theme_publication() +
  theme(axis.text.x = element_text(size = 12, face = "bold"))

ggsave("figures/descriptive/fig1_perception_distribution.png", fig1,
       width = 10, height = 6.5, dpi = 300, bg = "white")
cat("✓ Figure 1 saved to 'figures/descriptive/'\n")

# FIGURE 2: Temporal Evolution of Perceptions
cat("Figure 2: Temporal Evolution of Perceptions...\n")
df_meps$year <- as.numeric(substr(df_meps$event_date, 1, 4))
fig2_data <- df_meps %>%
  count(year, Perception.IA) %>%
  mutate(Perception.IA = factor(Perception.IA, levels = c("Pessimist", "Mixed", "Optimist", "Contextual")))

fig2 <- ggplot(fig2_data, aes(x = year, y = n, group = Perception.IA,
                              color = Perception.IA, linetype = Perception.IA)) +
  geom_line(linewidth = 1.2, alpha = 0.9) +
  geom_point(size = 2.5, alpha = 0.9) +
  scale_color_manual(
    values = c("Pessimist" = "black", "Mixed" = "gray40", "Optimist" = "gray60", "Contextual" = "gray85"),
    name = "AI Perception"
  ) +
  scale_linetype_manual(
    values = c("Pessimist" = "solid", "Mixed" = "dashed", "Optimist" = "dotted", "Contextual" = "dotdash"),
    name = "AI Perception"
  ) +
  scale_x_continuous(breaks = seq(2014, 2024, 1), name = "Year") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)), name = "Number of Interventions", breaks = seq(0, 150, 10)) +
  geom_vline(xintercept = 2022.9, linetype = "dashed", color = "#F26F52", linewidth = 0.8, alpha = 0.7) +
  annotate("text", x = 2022.9, y = max(fig2_data$n) * 0.95,
           label = "ChatGPT released\nto public", hjust = -0.1, size = 3.5, fontface = "bold", color = "#F26F52") +
  geom_vline(xintercept = 2021.0, linetype = "dashed", color = "#006FD6", linewidth = 0.8, alpha = 0.7) +
  annotate("text", x = 2021.0, y = max(fig2_data$n) * 0.75,
           label = "Toeslagenaffaire", hjust = -0.1, size = 3.5, fontface = "bold", color = "#006FD6") +
  labs(
    title = "Temporal Evolution of AI Perceptions (2014-2024)",
    subtitle = "MEPs only • Line chart for clarity"
  ) +
  theme_publication() +
  theme(legend.position = "right", axis.text.x = element_text(angle = 0, hjust = 0.5, size = 9))

ggsave("figures/descriptive/fig2_temporal_evolution.png", fig2,
       width = 11, height = 6, dpi = 300, bg = "white")
cat("✓ Figure 2 saved to 'figures/descriptive/'\n")

# FIGURE 3: Perceptions by Political Group
cat("Figure 3: Perceptions by Political Group...\n")
# Note: h1_analysis_features.csv only contains Pessimist, Mixed, Optimist (not Contextual)
# because Contextual was filtered out for the regression analysis
df_meps_scored <- df_lr %>%
  filter(Perception.IA %in% c("Optimist", "Pessimist", "Mixed")) %>%
  filter(!is.na(weighted_position) & total_meps >= 20)

# Calculate percentages for each perception category by group
fig3_data <- df_meps_scored %>%
  group_by(speaker_polgroup_clean, weighted_position) %>%
  summarise(
    n_total = n(),
    pct_pessimist = mean(Perception.IA == "Pessimist") * 100,
    pct_mixed = mean(Perception.IA == "Mixed") * 100,
    pct_optimist = mean(Perception.IA == "Optimist") * 100,
    .groups = 'drop'
  ) %>%
  filter(n_total >= 10) %>%
  arrange(desc(pct_optimist))  # Order from most optimistic to most pessimistic

# Abbreviate group names and pivot data for plotting
fig3_data_pivot <- fig3_data %>%
  mutate(
      group_short = case_when(
        grepl("Progressive Alliance", speaker_polgroup_clean) ~ "S&D",
        grepl("European People's Party", speaker_polgroup_clean) ~ "EPP",
        grepl("Greens", speaker_polgroup_clean) ~ "Greens/EFA",
        grepl("Left Group", speaker_polgroup_clean) ~ "GUE/NGL",
        grepl("Renew", speaker_polgroup_clean) ~ "Renew",
        grepl("Conservatives", speaker_polgroup_clean) ~ "ECR",
        grepl("Identity", speaker_polgroup_clean) ~ "ID",
        grepl("Non-attached", speaker_polgroup_clean) ~ "Non-attached\nMembers",
        TRUE ~ speaker_polgroup_clean
      ),
      group_short = factor(group_short, levels = unique(group_short))  # Keep order from arrange(desc(pct_optimist))
  )

fig3_long <- fig3_data_pivot %>%
  pivot_longer(cols = c("pct_pessimist", "pct_mixed", "pct_optimist"), names_to = "perception_type", values_to = "percentage") %>%
  mutate(
    perception_clean = case_when(
      perception_type == "pct_pessimist" ~ "Pessimist",
      perception_type == "pct_mixed" ~ "Mixed",
      perception_type == "pct_optimist" ~ "Optimist"
    ),
    perception_clean = factor(perception_clean, levels = c("Pessimist", "Mixed", "Optimist"))
  )
  
fig3 <- ggplot(fig3_long, aes(x = group_short, y = percentage, fill = perception_clean)) +
  geom_col(position = "stack", color = "white", linewidth = 0.3, width = 0.8) +
  scale_fill_manual(
    values = c("Pessimist" = "gray10", "Mixed" = "gray50", "Optimist" = "gray70"),
    name = "AI Perception"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), name = "Percentage of Interventions", expand = expansion(mult = c(0, 0.05))) +
  scale_x_discrete(name = "Political Group") +
  labs(
    title = "AI Perceptions by Political Group",
    subtitle = "Groups with ≥10 interventions, ordered from Most Optimistic to Most Pessimistic"
  ) +
  theme_publication() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12), legend.position = "right")

ggsave("figures/descriptive/fig3_perceptions_by_polgroup.png", fig3, width = 11, height = 7, dpi = 300, bg = "white")
cat("✓ Figure 3 saved to 'figures/descriptive/'\n\n")

# 6. SUMMARY TABLES ----------------------------------------------------------
cat("--- STEP 4: Generating Summary Tables ---\\n")
if (!dir.exists("output")) dir.create("output")

# Table 1: Data Overview
overview_table <- data.frame(
  Category = c("Total interventions", "MEPs interventions", "Others (Commissioners, guests)",
               "With AI perception coded (incl. Contextual)", "Pre-ChatGPT (2014-2022, MEPs)", "Post-ChatGPT (2023-2024, MEPs)"),
  N = c(nrow(df), sum(df$is_mep), sum(!df$is_mep), nrow(df_meps),
        sum(df_meps$year < 2023, na.rm = TRUE), sum(df_meps$year >= 2023, na.rm = TRUE))
)
write.csv(overview_table, "output/table_data_overview.csv", row.names = FALSE)
cat("✓ Data overview table saved.\n")

# Table 2: Perception Distribution (MEPs)
write.csv(perception_meps, "output/table_perception_distribution.csv", row.names = FALSE)
cat("✓ Perception distribution table saved.\n")

# Table 3: Data for Figure 3
if (exists("fig3_data_pivot")) {
  write.csv(fig3_data_pivot, "output/table_perceptions_by_polgroup.csv", row.names = FALSE)
  cat("✓ Perceptions by political group table saved.\n")
}

cat("\n======================================================\n")
cat("✓ SCRIPT 03 COMPLETE\n")
cat("======================================================\n")
